#!/usr/bin/env bash
# Configure a Nginx server to redirect to another page with '/redirect_me'
sudo apt-get -y update
sudo apt-get -y install nginx
mkdir -p /var/www/html
sudo service nginx start
sudo sh -c 'echo "Holberton School for the win!" > /var/www/html/index.html'
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
