#!/usr/bin/env bash
# Installs HAProxy version 1.8
sudo apt-get -y update
sudo apt-get -y install haproxy

echo "
frontend haproxynode
    bind *:80
    mode http
    default_backend backendnodes
backend backendnodes
    balance roundrobin
    server 2553-web-01 34.139.228.214:80 check
    server 2553-web-02 34.75.185.97:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy reload
sudo service haproxy restart
