#!/usr/bin/env bash
# A script that creates and deletes a file containing the PID
# Also displays different things depending on the command
echo $$ > /var/run/holbertonscript.pid
rmfile_exit()
{
    rm -f /var/run/holbertonscript.pid;
    exit
}
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rmfile_exit" SIGTERM
trap "echo 'I hate the kill command'; rmfile_exit" SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
