#!/usr/bin/env bash
# A script that prints "To infinity and beyond" indefinitely
# And "I am invincible!!!" when receiving a kill signal
trap "echo 'I am invincible!!!'" SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
