#!/usr/bin/env bash
# A script that displays numbers 1 to 100, exceptions:
# "FizzBuzz" for multiples of 3 and 5
# "Fizz" for multiples of 3
# "Buzz" for multiples of 5
for (( i=1; i <= 100; i++ ))
do
    if (( i % 15 == 0 )); then
	    echo "FizzBuzz"
    elif (( i % 3 == 0 )); then
	    echo "Fizz"
    elif (( i % 5 == 0 )); then
	    echo "Buzz"
    else
	    echo "$i"
    fi
done
