#!/usr/bin/env bash
# This scrip displays "Holberton School" 9 times and "Hi on the 9th time
i=1
while [ $i -le 10 ]
do
    echo "Holberton School"
    if [ $i -eq 9 ]; then
	    echo "Hi"
    fi
    (( i++ ))
done
