#!/usr/bin/env bash
# This script displays "Holberton School" 10 times, "bad luck" on the 4th,
# "good luck" on the 8th
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]; then
        echo "bad luck"
    elif [ $i -eq 8 ]; then
	    echo "good luck"
    else
	    echo "Holberton School"
    fi
    (( i++ ))
done
