#!/usr/bin/env bash
# A bash script that displays the content in the current directory
# in list format where only the part of the name after the first dash is displayed
files=$(ls)
for f in $files; do
    echo "$f" | cut -d "-" -f2
done
